### ISSUE TITLE
[InvalidOperationException: Unexpected sub-type: System.String]

### ISSUE THREAD

**Issue by jgeurts** [kevin-montrose/public-broadcasting#4]
Not sure if this is publicbroadcasting or protobuf, but this is the stack trace:

```
[InvalidOperationException: Unexpected sub-type: System.String]
   ProtoBuf.Meta.TypeModel.ThrowUnexpectedSubtype(Type expected, Type actual) in c:\Dev\protobuf-net\protobuf-net\Meta\TypeModel.cs:1335
   proto_3(Object , ProtoWriter ) +47
   ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest) in c:\Dev\protobuf-net\protobuf-net\Serializers\CompiledSerializer.cs:53
   ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest) in c:\Dev\protobuf-net\protobuf-net\Meta\RuntimeTypeModel.cs:760
   ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer) in c:\Dev\protobuf-net\protobuf-net\ProtoWriter.cs:46
   proto_5(Object , ProtoWriter ) +96
   ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest) in c:\Dev\protobuf-net\protobuf-net\Serializers\CompiledSerializer.cs:53
   ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest) in c:\Dev\protobuf-net\protobuf-net\Meta\RuntimeTypeModel.cs:760
   ProtoBuf.ProtoWriter.WriteObject(Object value, Int32 key, ProtoWriter writer) in c:\Dev\protobuf-net\protobuf-net\ProtoWriter.cs:46
   proto_1(Object , ProtoWriter ) +564
   ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Write(Object value, ProtoWriter dest) in c:\Dev\protobuf-net\protobuf-net\Serializers\CompiledSerializer.cs:53
   ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest) in c:\Dev\protobuf-net\protobuf-net\Meta\RuntimeTypeModel.cs:760
   ProtoBuf.Meta.TypeModel.SerializeCore(ProtoWriter writer, Object value) in c:\Dev\protobuf-net\protobuf-net\Meta\TypeModel.cs:186
   ProtoBuf.Meta.TypeModel.Serialize(Stream dest, Object value, SerializationContext context) in c:\Dev\protobuf-net\protobuf-net\Meta\TypeModel.cs:217
   ProtoBuf.Meta.TypeModel.Serialize(Stream dest, Object value) in c:\Dev\protobuf-net\protobuf-net\Meta\TypeModel.cs:201
   PublicBroadcasting.Impl.Envelope.Get(TypeDescription desc, POCOBuilder mapper, Object payload) in c:\Users\kmontrose\Dropbox\PublicBroadcasting\PublicBroadcasting\Impl\Envelope.cs:45
   PublicBroadcasting.Serializer.Serialize(Stream stream, T obj, IncludedMembers members, IncludedVisibility visibility) in c:\Users\kmontrose\Dropbox\PublicBroadcasting\PublicBroadcasting\Serializer.cs:248
   PublicBroadcasting.Serializer.Serialize(T obj, IncludedMembers members, IncludedVisibility visibility) in c:\Users\kmontrose\Dropbox\PublicBroadcasting\PublicBroadcasting\Serializer.cs:119
   PublicBroadcasting.Serializer.Serialize(T obj) in c:\Users\kmontrose\Dropbox\PublicBroadcasting\PublicBroadcasting\Serializer.cs:34
```

The object I'm trying to serialize looks like:

``` csharp
public class ActionSettings
{
    public string ActionName { get; set; }
    public string ControllerName { get; set; }
    public RouteValueDictionary RouteValues { get; set; }
}
```

Hope this helps and please let me know if I can provide any other details

**Comment by kevin-montrose** [comment]
I _suspect_ the problem here is `RouteValueDictionary` is an `IDictionary<string, object>`, which probably greatly confuses deserialization.

I haven't time to investigate further though, hopefully this weekend I'll get the free time.

**Comment by jgeurts** [comment]
Not a huge rush - I modified my code to convert the `RouteValueDictionary` to a `Dictionary<string, object>` shim and then when I deserialize, convert the shim back to a `RouteValueDictionary`.

**Comment by kevin-montrose** [comment]
@jgeurts `Dictionary<string, object>`?  Are you sure you didn't use `Dictionary<string, string>` for your shim?

It looks like the issue is `object` as the dictionary's TValue type (really just `System.Object` as a discovered "to be serialized" type, at all), protobuf doesn't know what to do with that (it has no properties or fields to annotate).  I _could_ make it not fail, but since no properties would be deserialized you'd just get a dictionary like `{ { "some value", new object() }, { "some other value", new object() }, ... }` out.

But if you've got working code with a `Dictionary<string, object>` shim, that kind of kills that theory.  Would love to see some more code if that's the case.

**Comment by jgeurts** [comment]
@kevin-montrose I apologize - I was trying to get the serialization working with Public Broadcasting and then TypeSerializer from service stack. I apparently settled on TypeSerializer, which handles the `Dictionary<string,object>` type. Added a test with #6, if that helps. Please let me know if I can help with anything else.

**Comment by kevin-montrose** [comment]
@jgeurts Yeah, protocol buffers can't really deal with heterogeneous collections.  I think the best thing to do here is to generate a better error message.

I think the way ServiceStack deals with this is by attaching type information to every stored value whose compile time type `System.Object`, which doesn't work with Public Broadcasting's "leading type description" approach.

I suppose I could detect when a collection is typed `System.Object` but actually contains only a single type (probably as a defaults-off option).  That wouldn't do anything for #6 though.

**Comment by jgeurts** [comment]
Ok, thanks for taking a bit of time on this. I do think that heterogeneous collections are a bit of an edge case and in my instance, I'm completely fine using a `Dictionary<string,string>` as an alternative.

As a side note, I looked at the serialized result from ServiceStack's [TypeSerializer](https://code.google.com/p/servicestack/wiki/TypeSerializer) and it didn't include the `__type` property with type information for each value. When deserializing, it just recreates the objects as strings.
